### ISSUE TITLE
Complete code?

### ISSUE THREAD

**Issue by wassimea** [gitmehrdad/SFSORT#1]
Hello, thank you for the interesting work. Any plans to release the full source code with demos to show how to run the tracker? Thanks

**Comment by kennyvoo** [comment]
Hello, Thank you for the great work. I'm also interested in this. Do you mind sharing the arguments parameters first?

**Comment by gitmehrdad** [comment]
Dear Wassim and Kenny,

Thank you both immensely. I've uploaded a notebook demonstrating an example of using SFSORT in conjunction with YOLOv8n. Additionally, I've included the YOLOv8n model weights and a sample video utilized within the notebook.
