### ISSUE TITLE
Which device was used in the speed comparison table?

### ISSUE THREAD

**Issue by Korzeniow** [gitmehrdad/SFSORT#4]
Thank you for releasing the new tracker. I am very interested in your research.

What is the experimental environment for the performance indicators in Figure 8 compared in the paper?

For example, what GPU were you using to get the results?

**Comment by gitmehrdad** [comment]
Thank you so much. As stated in the "Implementation Details" part of the paper, we evaluated the tracker using a 2.20GHz Intel(R) Xeon(R) CPU. All experiments, including speed measurements, were conducted using this CPU. While the tracking algorithm itself does not require a GPU, the object detector used in our experiments does necessitate one. Specifically, we employed a Tesla T4 GPU for this purpose.

Regarding the speed measurement experiment, you may find the following description helpful:

When calculating the tracking speed, I measured it from the moment the detections were delivered to the tracker until the IDs were received from the tracker, following the advice provided on the MOTChallenge website. Considering that background noise, such as that from the OS, server, IDE, etc., can impact measurement accuracy, the reported speed in the paper is the average speed obtained after several repetitions of the experiment. To measure the tracking speed, I utilized the "time" and "timedelta" packages in Python.

**Comment by Korzeniow** [comment]
Thank you for your valuable answer.

Conventional object tracking often follows the DeepSORT structure, and your contribution using BBSI without the Kalman filter was very impressive.
