### ISSUE TITLE
Small fast object track

### ISSUE THREAD

**Issue by kywish** [gitmehrdad/SFSORT#7]
If the target is small and moves quickly (4 of its own size move between frames). Can SFSORT work in this situation? How should I adjust the parameters?

**Comment by gitmehrdad** [comment]
Hi,

Yes, SFSORT can track objects in such a scenario. You should adjust the "match_th_first" and "match_th_second" parameters to relatively high values (e.g., 0.7). Don’t forget to fine-tune the object detector you are using. Also, I’m planning to update the repository in the near future, so keep an eye on it for more useful info and updated code.

**Comment by kywish** [comment]
Thanks~ 
I temporarily increase the size of the small target box to increase the IOU , thereby solving this problem.😂
