### ISSUE TITLE
`dynamic_tuning` arguments are being reset during the range validation phase

### ISSUE THREAD

**Issue by tchaloupka** [gitmehrdad/SFSORT#8]
Here: https://github.com/gitmehrdad/SFSORT/blob/c6068ef80f65db56081af3fcdf8613a6b083b9a7/SFSORT.py#L94
The provided args are set to 0 and next to 0.02 by the `clamp` function.
Also, this way, one cannot provide 0 to the dynamic tuning parameters as it would be clamped up to 0.02. Is it intentional?

**Comment by gitmehrdad** [comment]
Hi,

**Line 94**: The default value of `high_th_m` is set to `0`, which disables dynamic tuning for the `hth` parameter in the formula on line 152. This behavior is intended for cases where dynamic tuning is enabled, but the user does not wish to adjust the `hth` parameter. To achieve this, the user should not mention `high_th_m` during tracker instantiation.

**Line 102**: When the user enables dynamic tuning and wants the `hth` parameter to change dynamically, the code enforces that `high_th_m` remains within the range `(0.02, 0.1)`. My experiments indicate that values below `0.02` have negligible effect on tracking, while values above `0.1` push the conditions to their extremes.

**Comment by tchaloupka** [comment]
Thanks for the clarification.
My point is that when I for example provide these parameters:

```python
tracker_arguments = {"dynamic_tuning": True, "cth": 0.5,
                      "high_th": 0.6, "high_th_m": 0.1,
                      "match_th_first": 0.67, "match_th_first_m": 0.05,
                      "match_th_second": 0.2, "low_th": 0.1,
                      "new_track_th": 0.7, "new_track_th_m": 0.1,
                      "marginal_timeout": (7 * fps // 10),
                      "central_timeout": fps,
                      "horizontal_margin": width // 10,
                      "vertical_margin": height // 10,
                      "frame_width": width,
                      "frame_height": height}
```

It ends up using `match_th_first_m = 0.02` instead of the provided `0.05`.
There should probably be `self.match_th_first_m = 0.0` instead of `args.match_th_first_m = 0.0`

**Comment by gitmehrdad** [comment]
Oops, that's correct! The code has been updated now.
